### ISSUE TITLE
ERROR TypeError: this.elementRef.nativeElement.querySelector is not a function

### ISSUE THREAD

**Issue by mbn18** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#23]
Hi,

I installed the module (4.0.4) and it works on Angular 4.1.1

But it load slowly and the log is filled with this message repeated hundreds times:

    ERROR TypeError: this.elementRef.nativeElement.querySelector is not a function
        at SwiperComponent.setup (/srv/httpd/dist/server/webpack:/~/angular2-useful-swiper/lib/swiper.component.js:27:1)
        at SwiperComponent.ngAfterViewChecked (/srv/httpd/dist/server/webpack:/~/angular2-useful-swiper/lib/swiper.component.js:36:1)
        at callProviderLifecycles (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:11076:1)
        at callElementProvidersLifecycles (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:11048:1)
        at callLifecycleHooksChildrenFirst (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:11032:1)
        at checkAndUpdateView (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:12061:1)
        at callViewAction (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:12367:1)
        at execComponentViewsAction (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:12313:1)
        at checkAndUpdateView (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:12059:1)
        at callViewAction (/srv/httpd/dist/server/webpack:/~/@angular/core/@angular/core.es5.js:12367:1)

I tried Swiper `3.3.1` as mentioned in the README and the latest `3.4.2`

There are no more errors after the page is loaded and client finish the render. Not even if I go to different page and return.

Any idea?

Thanks

**Comment by mbn18** [comment]
Seems its only happens when  the server side render the component `url` (universal?)
No errors are logged when I load any other `url` and then browse to the components with the Swiper

**Comment by JayChase** [comment]
It looks like that call will cause problems with Universal. I'm testing a couple of options for making it Universal friendly at the moment. I'll keep this issue open and let you know how I get on.

**Comment by JayChase** [comment]
This is fixed by [pull request 24](https://github.com/Useful-Software-Solutions-Ltd/angular2-useful-swiper/pull/24).
